version: "3.9"

services:
  antink-server:
    build: .
    container_name: antink-server
    # Butuh privilege untuk akses FUSE
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    # Mount volume untuk data asli, mountpoint, dan log
    volumes:
      - original_data:/srv/antiNK/original:ro
      - fuse_mount:/srv/antiNK/mount
      - log_data:/srv/antiNK/logs

  antink-logger:
    image: ubuntu:22.04
    container_name: antink-logger
    depends_on:
      - antink-server
    # Install inotify-tools untuk monitoring real-time
    entrypoint: >
      sh -c "apt-get update &&
             apt-get install -y --no-install-recommends inotify-tools &&
             tail -n+1 -F /srv/antiNK/logs/it24.log"
    volumes:
      - log_data:/srv/antiNK/logs:ro

volumes:
  original_data:
    # volume kosong; isi file asli bisa di-copy via `docker cp`
  fuse_mount:
  log_data:
